- cmake/init_target.cmake
Flag `-msse2` should be used only on x86-32 platforms.
> Use -msse2 build flag only on x86-32 platforms

- cmake/init_target.cmake
Downgraded C++ version from C++20 to C++17 as a workaround to abseil-cpp upstream issue.
See also: https://github.com/abseil/abseil-cpp/issues/722
This will fix build under GCC 10+.
Closes #4.
> Downgraded C++ version from C++20 to C++17 due to abseil-cpp

- cmake/arch.cmake
- cmake/init_target.cmake
Currently, the build system assumes x86 (checking the pointer width for whether it's 32 bit or 64 bit), this commit provides a mechanism to detect the target CPU architecture based on platform-specific compile-time macros.
It checks for x86, x64, aarch64 and 32-bit arm (armv6 (or older), armv7, armv8).
> Implement compile-time arch detection using platform-specific macros.

- CMakeLists.txt
- cmake/libvpx.cmake
The libvpx.cmake file currently assumes x86.  This pull request (which depends on https://github.com/desktop-app/tg_owt/pull/19) makes it more general, and adds support for building on arm, both 32 and 64 bit, with or without NEON SIMD extensions.
This pull request also enables the ASM language in the main project file, which is required to compile the .S files (otherwise cmake just ignores them).
> Add support for building libvpx on arm.

- cmake/libyuv.cmake
While libyuv does build on arm as-is (if https://github.com/desktop-app/tg_owt/pull/19 - architecture detection, is present), the NEON SIMD extensions aren't used by default.  This pull request adds support for the bundled libyuv to be compiled with NEON SMID extensions enabled.
> Allow libyuv to be built with NEON SIMD.

- cmake/libopenh264.cmake
While libopenh264 does build on arm as-is (if https://github.com/desktop-app/tg_owt/pull/19 - architecture detection, is present), the NEON SIMD extensions aren't used by default.  This pull request adds support for the bundled libopenh264 to be compiled with NEON SMID extensions enabled.
This pull request also depends on https://github.com/desktop-app/tg_owt/pull/20, since that adds ASM to the list of used languages, which is required to compile the .S files (otherwise cmake just ignores them).
> Allow libopenh264 to be built with NEON SIMD.

- cmake/libpffft.cmake
Currently, libpffft always expects NEON on ARM platforms.  This behavior can be changed by defining the PFFFT_SIMD_DISABLE compile-time macro when building on ARM but NEON is not available, which is what this pull request does.
This pull request depends on https://github.com/desktop-app/tg_owt/pull/19 for architecture detection.
> Fix libpffft build failure on ARM platforms that don't support NEON.

- CMakeLists.txt
This is the final in the series of commits (split into separate pull requests on @vitlav's suggestion on https://github.com/desktop-app/tg_owt/pull/18) that adds support for building tg_owt on ARM and aarch64.
Together with the other commits (https://github.com/desktop-app/tg_owt/pull/19 https://github.com/desktop-app/tg_owt/pull/20 https://github.com/desktop-app/tg_owt/pull/21 https://github.com/desktop-app/tg_owt/pull/22 https://github.com/desktop-app/tg_owt/pull/23), I was able to build the library on a Raspberry Pi B+ (armv6) running Debian Buster, on an ARMv7 Android tablet with Debian Buster in a chroot, a repurporsed Motorola Moto G running PostmarketOS (armv7), as well as a Pine64 PinePhone (aarch64) running PostmarketOS, and of course, a desktop PC with a 64-bit x86 processor …
> Add support for building on ARM (32-bit and 64-bit), with or without NEON SIMD.

- cmake/external.cmake
Since FindPulseAudio requires extra-cmake-modules
> Find libpulse via pkg-config

- CMakeLists.txt
- cmake/libabsl.cmake
- cmake/libpffft.cmake
- cmake/libsdkmacos.cmake
- cmake/libsrtp.cmake
- cmake/libusrsctp.cmake
- cmake/libvpx.cmake
- cmake/libwebrtcbuild.cmake
- cmake/libyuv.cmake
Allow user to install and use the package rather than build and use it in-tree.
This make it easy to being packaged for package manager (though as an internal build dependency).
Related: https://github.com/NixOS/nixpkgs/pull/100450
> Support to be installed

- CMakeLists.txt
- cmake/protobuf/CMakeLists.txt
- src/logging/rtc_event_log/encoder/rtc_event_log_encoder_legacy.cc
- src/logging/rtc_event_log/encoder/rtc_event_log_encoder_new_format.cc
Use protobuf to generate missing sources and headers.
This will fix the following:
```
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `vtable for webrtc::RtcEventLogEncoderLegacy'
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `vtable for webrtc::RtcEventLogEncoderNewFormat'
collect2: error: ld returned 1 exit status
```
> Use protobuf to generate missing sources and headers

- CMakeLists.txt
Added missing fifo_buffer to build.
Fixes:
```
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `rtc::FifoBuffer::FifoBuffer(unsigned long)'
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `rtc::FifoBuffer::ReadOffset(void*, unsigned long, unsigned long, unsigned long*)'
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `rtc::FifoBuffer::GetWriteRemaining(unsigned long*) const'
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `rtc::FifoBuffer::WriteOffset(void const*, unsigned long, unsigned long, unsigned long*)'
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `rtc::FifoBuffer::Write(void const*, unsigned long, unsigned long*, int*)'
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference …
```
> Added missing fifo_buffer to build

- CMakeLists.txt
Respect BUILD_SHARED_LIBS with fallback to the previous behaviour for
the special target (official static binary).
To build tg_owt as a shared library, use `-DBUILD_SHARED_LIBS:BOOL=ON`.
If you want a static library, use `-DBUILD_SHARED_LIBS:BOOL=OFF`.
> Allow to build as a shared library

- cmake/libabsl.cmake
Should fix linkage issue for shared builds:
```
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `absl::raw_logging_internal::RawLog(absl::LogSeverity, char const*, int, char const*, ...)'
/usr/bin/ld: /usr/lib64/libtg_owt.so.0.0.0: undefined reference to `absl::raw_logging_internal::internal_log_function[abi:cxx11]'
```
> Added missing sources to the build

- CMakeLists.txt
Fixes the following:
```
$ cmake -DBUILD_SHARED_LIBS=OFF -DTG_OWT_USE_PROTOBUF=ON
-- Processor architecture is 64-bit x86.
-- Configuring done
CMake Error: install(EXPORT "tg_owtTargets" ...) includes target "tg_owt" which requires target "proto" that is not in any export set.
CMake Error in CMakeLists.txt:
export called with target "tg_owt" which requires target "proto" that is
not in any export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
> Export proto target when TG_OWT_USE_PROTOBUF is set

- cmake/libvpx.cmake
Bugfix for https://github.com/desktop-app/tg_owt/issues/48
Note: I wasn't able to test the full build because of the protobuf incompatibility in https://github.com/desktop-app/tg_owt/issues/43, but libvpx does indeed build now.
> Generate GAS-compatible 32-bit ARM ASM files for libvpx on Linux.

- CMakeLists.txt
- cmake/external.cmake
- cmake/libabsl.cmake
- cmake/libevent.cmake
- cmake/libopenh264.cmake
- cmake/libpffft.cmake
- cmake/librnnoise.cmake
- cmake/libsrtp.cmake
- cmake/libusrsctp.cmake
- cmake/libvpx.cmake
- cmake/libwebrtcbuild.cmake
- cmake/libyuv.cmake
- cmake/tg_owtConfig.cmake
- src/modules/video_coding/codecs/h264/h264_encoder_impl.cc
- src/modules/video_coding/codecs/h264/h264_encoder_impl.h
- src/rtc_base/task_queue_libevent.cc
This patch adds support for building tg_owt using system libraries
instead of bundled third_party modules.
Some libraries haven't been converted for the following reasons:
- pffft: No stable ABI, patched, and not available in major distributions.
- rnnoise: All of the remaining files are custom.
- libsrtp: This project uses private APIs.
- libyuv: No stable ABI, frequent breaking updates, and not available in major distributions.
Additionally, libvpx is currently bundled by default, because it
requires an unstable git version.
Note that: This still installs the system headers for the third_party
modules (albeit in a convenient sub-directory). I haven't figured out a
method to avoid this.
This would fix https://github.com/desktop-app/tg_owt/issues/52
I'm posting this Draft PR to receive …
> Add options to use packaged third_party

- cmake/libvpx.cmake
Turns out that `vpx_convolve8_neon.c` and `vpx_convolve_neon.c` of libvpx are not mutually exclusive with the 32-bit assembly files for NEON SIMD on ARM.  This patch adds them into the list of common source files between 32-bit and 64-bit NEON.
> Fix unresolved convolve8 symbols on 32-bit ARM with NEON SIMD.

- src/modules/desktop_capture/linux/screen_capturer_x11.cc
- src/modules/desktop_capture/linux/screen_capturer_x11.h
Since tdesktop links to XRandr statically, this has no sense
Fixes https://github.com/telegramdesktop/tdesktop/issues/16482
> Don't use dlsym with XRandr

- cmake/libwebrtcbuild.cmake
- src/rtc_base/byte_order.h
- src/rtc_base/ip_address.cc
- src/rtc_base/physical_socket_server.cc
- src/rtc_base/platform_thread_types.cc
- src/system_wrappers/source/cpu_info.cc
- Provide cmake variable and preprocessor define for FreeBSD.
- Treat FreeBSD different to Linux where they differ.
- Mark POSIX interfaces as POSIX and Linux as Linux with corresponding preprocessor define.
> Set of patches to compile and properly work on FreeBSD

- src/modules/desktop_capture/linux/egl_dmabuf.cc
- src/rtc_base/platform_thread_types.cc
It is also unportable, but less legacy than thr_self().  It also
provides 32-bit return value, which matches PlatformThreadId on
all POSIX platforms of tg_owt.
Fixes:	27518db9
Fixes:	fa608fc9
> Use pthread_getthreadid_np() on FreeBSD.

- src/modules/video_capture/linux/device_info_linux.cc
- src/modules/video_capture/linux/video_capture_linux.cc
video(4) provides everything needed, the Linux header does not exist.
Tested on OpenBSD/amd64 7.0 -CURRENT.
> video_capture: Use correct V4L2 header on OpenBSD

- src/modules/rtp_rtcp/source/rtp_packetizer_av1_test_helper.h
Fixed build on GCC 12 by adding missing includes.
> GCC 12 build fixes

- cmake/libusrsctp.cmake
- cmake/libwebrtcbuild.cmake
- src/rtc_base/byte_order.h
- src/rtc_base/platform_thread_types.cc
- src/rtc_base/platform_thread_types.h
These are required to build on OpenBSD/amd64 7.0 -CURRENT.
Both `net/tg_owt` and `net/tdesktop` have been ported to OpenBSD and widely tested already.
`tg_owt` is built as shared library and I'd like to avoid carrying local patches as best as possible.
> Build on OpenBSD

- CMakeLists.txt
- src/modules/desktop_capture/linux/egl_dmabuf.h
webrtc seem to manually load GL libraries with dlopen, so epoxy is actually unused
> Remove epoxy dependency

- CMakeLists.txt
- cmake/libwebrtcbuild.cmake
Squashed commit of the following:
commit 253b09a07520a3cecb3b88b2b7e8889ab3d9158d
Author: Hilton Chain <hako@ultrarare.space>
Date:   Fri Sep 9 22:13:15 2022 +0800
Adapt the patch with cmake_dependent_option.
commit f6631bb43f353c9eafe1b1aba093e116518aa12a
Author: Esteve Varela Colominas <esteve.varela@gmail.com>
Date:   Sun, 27 Jun 2021 23:57:04 +0200
Add -DTG_OWT_USE_X11
Allows disabling X11 desktop capturing independently of pipewire support, for
the few people that run wayland without any X11 support whatsoever.
This setup is untested, but supported by the GNI build system, see:
* src/modules/desktop_capture/BUILD.gn (option rtc_use_x11_extensions)
Toggling the WEBRTC_USE_X11 define also affects some files under
src/modules/audio_device, but that falls under "X11 support", …
> Allow disabling X11 desktop capturing independently.

- src/modules/video_coding/codecs/h264/h264_encoder_impl.cc
- src/modules/video_coding/codecs/h264/h264_encoder_impl.h
99edacee "Update: Copy updated source files (M108+H265)." changed those
to the bundled headers, but `cmake/libopenh264.cmake` does create a
public "wels/" include directory, i.e. building with `<wels/*.h>` works
with both external/system/packages and bundled openh264 alike.
Revert the includes to unbreak the tg_owt build on OpenBSD where unused
`third_party/` content is removed to prevent accidential use like this.
> Patch: Use public/system h264 includes

- CMakeLists.txt
Fix build without PipeWire
Avoid building PipeWire specific builds unless `TG_OWT_USE_PIPEWIRE` is true.
This unbreaks OpenBSD's tg_owt build.
> CMake: Fix build without PipeWire

- src/modules/video_capture/linux/device_info_v4l2.cc
- src/modules/video_capture/linux/video_capture_v4l2.cc
The other two v4l2 files already have this define, see merged
https://github.com/desktop-app/tg_owt/pull/81
```
commit 62b67d5ca6fa9e8b9f813fd7d715e0e4cf908dfb
Patch: video_capture: Use correct V4L2 header on OpenBSD
video(4) provides everything needed, the Linux header does not exist.
Tested on OpenBSD/amd64 7.0 -CURRENT.
```
> Patch: Use video(4) <sys/videoio.h> on OpenBSD

- cmake/external.cmake
It's used in headers, it should be public
> Fix libabsl packaged scope

- src/modules/desktop_capture/linux/wayland/shared_screencast_stream.cc
As per man 2 fcntl:
> fcntl() can take an optional third argument.  Whether or not this
>        argument is required is determined by cmd.  The required argument
>        type is indicated in parentheses after each cmd name (in most
>        cases, the required type is int, and we identify the argument
>        using the name arg), or void is specified if the argument is not
>        required.
> ...
> F_DUPFD_CLOEXEC (int; since Linux 2.6.24)
After this fix, screensharing starts working with wayland + pipewire.
Before it was failing due to garbage in required argument.
> strace -e fcntl telegram-desktop
> ...
> fcntl(136, F_DUPFD_CLOEXEC, 140469472426232) = -1 EINVAL (Invalid argument)
> Fix fcntl call.

- src/modules/desktop_capture/linux/wayland/shared_screencast_stream.cc
The issues is observed in [telegram-desktop](https://github.com/telegramdesktop/tdesktop). The patch is taken from upstream webrtc with `observer_` related code removed since our branch does not have that.
Upstream patch: https://webrtc-review.googlesource.com/c/src/+/349881
Upstream bug: https://issues.webrtc.org/issues/338232699
> Fix screencast glitching on KDE6/wayland when moving the cursor

- src/modules/video_capture/video_capture_options.h
Despite the name, Video-for-Linux is used on OpenBSD and FreeBSD as well.
As per `cmake/libwebrtcbuild.cmake`, all supported UNIX systems except Apple.
Fixes this:
```
.../src/modules/video_capture/linux/video_capture_linux.cc:63:16: error: no member named 'allow_v4l2' in 'webrtc::VideoCaptureOptions'
if (options->allow_v4l2()) {
~~~~~~~  ^
1 error generated.
```
> Fix V4L2 build in WebRTC for BSDs

- src/rtc_base/net_test_helpers.cc
```
.../src/rtc_base/net_test_helpers.cc:41:50: error: member access into incomplete type 'struct sockaddr'
if (cur->ifa_addr != nullptr && cur->ifa_addr->sa_family == AF_INET) {
```
> Include all getifaddrs(3) headers to unbreak build on OpenBSD

- CMakeLists.txt
Fixes OpenBSD's build:
```
.../src/modules/video_capture/linux/pipewire_session.h:14:10: fatal error: 'pipewire/core.h' file not found
```
glib-2.0 is only ever a transitive dependency for PipeWire:
```
.../src/modules/video_capture/linux/camera_portal.cc:13:10: fatal error: 'gio/gio.h' file not found
```
> Skip all PipeWire files under TG_OWT_USE_PIPEWIRE:BOOL=OFF

- cmake/init_target.cmake
This commit fixes the following compiler errors.
c++.exe: warning: /W1: linker input file unused because linking not done
c++.exe: error: /W1: linker input file not found: No such file or directory
c++.exe: warning: /wd4715: linker input file unused because linking not done
c++.exe: error: /wd4715: linker input file not found: No such file or directory
> CMake: Prevent adding MSVC compiler flag with mingw toolchain

- CMakeLists.txt
- cmake/external.cmake
- src/pc/external_hmac.cc
- src/pc/external_hmac.h
- src/pc/srtp_session.cc
Avoid private symbols and link against system-wide libSRTP. The excluded code in SrtpSession looks unreachable from the call integration in Telegram Desktop.
Rebased version of #123 where the author blocked tg_owt developers, thus hindering progress...
OpenBSD has used this PR since inception, no complaints/problems with audio/video calls so far using liibSRTP 2.6.0.
> Unbundle libSRTP

- src/modules/video_capture/linux/pipewire_session.cc
Fixes #148.
Caused by https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/188d920733f0791413d3386e5536ee7377f71b2f.
> Fix mismatching pipewire types

- cmake/tg_owtConfig.cmake
It stops the execution of config file by default while with REQUIRED it stops execution of the entire cmake configuration
> CMake: Don't use REQUIRED with find_dependency

- cmake/libwebrtcbuild.cmake
Looks like there's no way to force cmake to write evaluated value rather than generator expression itself to the exported target
> Aim to synchronize NDEBUG with own build type
